=== Hasan-Hawar/JavaProjects/oop2-workspace/Excercise4_06/Persons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="https://bfh.ch/BTI7055q" 
	xmlns:oop2="https://bfh.ch/BTI7055q"
	attributeFormDefault="qualified" elementFormDefault="qualified">
	
	<xsd:simpleType name="MaritalStatus">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="SINGLE"/>
			<xsd:enumeration value="MARRIED"/>
			<xsd:enumeration value="CIVIL_PARTNERSHIP" />
			<xsd:enumeration value="DIVORCED" />
			<xsd:enumeration value="WIDOWED" />
			<xsd:enumeration value=""></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="PersonType">
		<xsd:sequence>
			<xsd:element name="Name" type="xsd:string"/>
			<xsd:element name="FirstName" type="xsd:string"/>
			<xsd:element name="Birthdate" type="xsd:date"/>
			<xsd:element name="MaritalStatus" type="oop2:MaritalStatus"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="PersonsType">
		<xsd:sequence>
			<xsd:element name="Person" type="oop2:PersonType" maxOccurs="unbounded"
			 minOccurs="0">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:element name="Persons" type="oop2:PersonType"></xsd:element>

</xsd:schema>

=== Hasan-Hawar/JavaProjects/oop2-workspace/Excercise4_06/PersonXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<OOP2:Persons
	xmlns:oop2="https://bfh.ch/BTI7055q"
	xmlns:xsi="http:www.w3.org/2001/XMLSchema-instance"
	xsi:xsi:schemaLocation="https://bfh.ch/BTI7055q Persons.xsd"
	oop2:version="FS2019">
	
	<oop2:Persons>
		<oop2:Name>Duck</oop2:Name>
		<oop2:FirstName>Donald</oop2:FirstName>
		<oop2:Birthdate>1920-04-13</oop2:Birthdate>
		<oop2:MaritalStatus>SINGLE</oop2:MaritalStatus>
	</oop2:Persons>
	<oop2:Persons>
		<oop2:Name>Luke</oop2:Name>
		<oop2:FirstName>Lucky</oop2:FirstName>
		<oop2:Birthdate>1946-11-14</oop2:Birthdate>
		<oop2:MaritalStatus>SINGLE</oop2:MaritalStatus>
	</oop2:Persons>
	<oop2:Persons>
		<oop2:Name>Dalton</oop2:Name>
		<oop2:FirstName>Mac</oop2:FirstName>
		<oop2:Birthdate>1958-01-01</oop2:Birthdate>
		<oop2:MaritalStatus>WIDOWED</oop2:MaritalStatus>
	</oop2:Persons>	
</OOP2:Persons>
